import os
from collections import defaultdict

def _prf(tp, fp, fn):
    prec = tp / (tp + fp) if (tp + fp) else 0.0
    rec = tp / (tp + fn) if (tp + fn) else 0.0
    f1 = (2 * prec * rec) / (prec + rec) if (prec + rec) else 0.0
    return prec, rec, f1

def test_generate_markdown_report(results_recorder):
    """
    After all tests have run, aggregate the collected results
    and save them into a Markdown file (tests/test_results.md).
    """
    rows = results_recorder["rows"]
    if not rows:
        # Skip silently if nothing was recorded
        return

    stats = defaultdict(lambda: {"tp": 0, "fp": 0, "fn": 0, "n": 0})

    for r in rows:
        cat, got, exp = r["cat"], r["got"], r["expected"]
        stats[cat]["n"] += 1

        if got == exp:
            stats[cat]["tp"] += 1
        elif exp == "PASS" and got in ("BLOCK", "ASK"):
            stats[cat]["fp"] += 1
        elif exp in ("BLOCK", "ASK") and got == "PASS":
            stats[cat]["fn"] += 1
        else:
            stats[cat]["fp"] += 1

    # Build Markdown table
    lines = [
        "# Guardrails Evaluation Results\n",
        "| Category | N | TP | FP | FN | Precision | Recall | F1 |",
        "|---|---:|---:|---:|---:|---:|---:|---:|",
    ]

    for cat, s in stats.items():
        p, r, f = _prf(s["tp"], s["fp"], s["fn"])
        lines.append(
            f"| {cat} | {s['n']} | {s['tp']} | {s['fp']} | {s['fn']} "
            f"| {p:.2f} | {r:.2f} | {f:.2f} |"
        )

    # Overall micro-average
    tp = sum(s["tp"] for s in stats.values())
    fp = sum(s["fp"] for s in stats.values())
    fn = sum(s["fn"] for s in stats.values())
    p, r, f = _prf(tp, fp, fn)
    total = sum(s["n"] for s in stats.values())
    lines.append(f"| **overall** | {total} | {tp} | {fp} | {fn} | {p:.2f} | {r:.2f} | {f:.2f} |")

    lines.append("\nThis file is automatically generated by pytest.\n")

    # Write results to a Markdown file
    out_path = os.path.join(os.path.dirname(__file__), "test_results.md")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
